spring.config.import=configserver:http://config-server:8888

spring.application.name=capstone

spring.jpa.show-sql=true
server.port=8080
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

eureka.client.registry-fetch-interval-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

spring.cloud.config.fail-fast=true

management.endpoints.web.exposure.include=*

logging.level.org.springframework.cloud=DEBUG