spring.application.name=capstone
spring.config.import=optional:configserver:http://localhost:8888
spring.jpa.show-sql=true
server.port=8000
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka